Create a tool to apply Labeler to a list of events.
world-federation-of-advertisers/virtual_people_examples pull request #11
Opened 2021-07-23 21:13 UTC by tcsnfkx

2021-07-23 21:27 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/11)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/model_applier/model_applier.cc, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/11#-MfKFEeU6nPu80QSpw1s:-MfKFEeU6nPu80QSpw1t:bui98lc) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/e26bb0e8b30a1a45005fb44cff87bb7d7ac0b0e3/src/main/cc/wfa/virtual_people/model_applier/model_applier.cc#L103)):*
> ```cpp
>     CHECK(labeler.ok())
>         << "Creating Labler failed with status: " << labeler.status();
>     return std::move(*labeler);
> ```

Nit: `*std::move(labeler)`
___
*[src/main/cc/wfa/virtual_people/model_applier/model_applier.cc, line 113 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/11#-MfKFHo-Db_w_oO9zCtv:-MfKFHo-Db_w_oO9zCtw:bui98lc) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/e26bb0e8b30a1a45005fb44cff87bb7d7ac0b0e3/src/main/cc/wfa/virtual_people/model_applier/model_applier.cc#L113)):*
> ```cpp
>     CHECK(labeler.ok())
>         << "Creating Labler failed with status: " << labeler.status();
>     return std::move(*labeler);
> ```

Nit: `*std::move(labeler)`
___
*[src/main/cc/wfa/virtual_people/model_applier/model_applier.cc, line 139 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/11#-MfKFcxV2OprWYcjWhFp:-MfKFcxV2OprWYcjWhFq:b-5ns7bv) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/e26bb0e8b30a1a45005fb44cff87bb7d7ac0b0e3/src/main/cc/wfa/virtual_people/model_applier/model_applier.cc#L139)):*
> ```cpp
> // @count represents the number of added virtual person.
> // @virtual_person_ids represents the set of unique virtual person ids.
> struct AggregatedRow {
> ```

https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes -- this should not be a struct because there's an invariant between the two fields.

But also, can you just use `virtual_person_ids.size()` to get the count?


<!-- Sent from Reviewable.io -->

2021-07-24 04:47 UTC, tcsnfkx reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/11)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/model_applier/model_applier.cc, line 139 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/11#-MfKFcxV2OprWYcjWhFp:-MfLpIi5C1bOCCCFkbzw:b4gyq6l) ([raw file](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/e26bb0e8b30a1a45005fb44cff87bb7d7ac0b0e3/src/main/cc/wfa/virtual_people/model_applier/model_applier.cc#L139)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes -- this should not be a struct because there's an invariant between the two fields.

But also, can you just use `virtual_person_ids.size()` to get the count?
</blockquote></details>

Changed to class. virtual_person_ids_ is a set. count_ is the count of the virtual_person_ids added, while virtual_person_ids_.size() is the count of the unique virtual_person_ids.


<!-- Sent from Reviewable.io -->

2021-07-24 05:32 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual_people_examples/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)



<!-- Sent from Reviewable.io -->

2021-07-26 15:33 UTC, mpatel24 approved these changes

2021-07-30 15:31 UTC, merged